Repository seohyeon2/ios-open-market, pull requests merged in 2022-07, with the labels that each got.

#1 STEP1-2 PR(Mockdata Test)
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Assets.xcassets/products.dataset/62cba0444113154855988ca5 (1).json
  OpenMarket/OpenMarket/Assets.xcassets/products.dataset/Contents.json
  OpenMarket/OpenMarket/Model/MarketInformation.swift
  OpenMarket/OpenMarket/Model/Mock/MockURLSession.swift
  OpenMarket/OpenMarket/Model/Mock/MockURLSessionDataTask.swift
  OpenMarket/OpenMarket/Model/NetworkError.swift
  OpenMarket/OpenMarket/Model/NetworkManager.swift
  OpenMarket/OpenMarket/Model/URLSessionDataTaskProtocol.swift
  OpenMarket/OpenMarket/Model/URLSessionProtocol.swift
  OpenMarket/OpenMarketTests/OpenMarketTests.swift
Labels: feat, test

#2 STEP1-2 PR(feat : getProductList Method)
  OpenMarket/OpenMarket/Model/Mock/MockURLSession.swift
  OpenMarket/OpenMarket/Model/NetworkManager.swift
  OpenMarket/OpenMarket/Model/URLSessionProtocol.swift
  OpenMarket/OpenMarket/ViewController.swift
  OpenMarket/OpenMarketTests/OpenMarketTests.swift
Labels: feat, fix

#3 STEP2-1 PR(컬렉션뷰 구현)
  OpenMarket/MainViewController.swift
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Base.lproj/Main.storyboard
  OpenMarket/OpenMarket/CollectionViewCell/GridCollectionViewCell.swift
  OpenMarket/OpenMarket/CollectionViewCell/ItemCollectionViewCell.swift
  OpenMarket/OpenMarket/CollectionViewCell/ListCollectionViewCell.swift
  OpenMarket/OpenMarket/Extension/String + extension.swift
  OpenMarket/OpenMarket/Model/MarketInformation.swift
  OpenMarket/OpenMarket/Model/NameSpace/CollectionViewNamespace.swift
  OpenMarket/OpenMarket/Model/NameSpace/ModelNameSpace.swift
  OpenMarket/OpenMarket/ViewController.swift
  README.md
Labels: feat
